# Generated by Django 5.2.4 on 2025-11-07 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_auditoriainstitucion_auditoriainternacion_and_more'),
        ('profesional', '0003_alter_profesional_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaprofesional',
            name='nombre_profesional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriaprofesional',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='profesional.profesional'),
        ),
    ]
