# Generated by Django 5.2.4 on 2025-11-11 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_auditoriaprofesional_nombre_profesional_and_more'),
        ('expediente', '0019_expedienteinstitucion_unique_expediente_institucion_rol_and_more'),
        ('institucion', '0001_initial'),
        ('internacion', '0007_rename_posse_adiccion_internacion_posee_adiccion'),
        ('intervencion', '0003_alter_intervencion_options_and_more'),
        ('persona', '0004_alter_persona_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaexpediente',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='expediente.expediente'),
        ),
        migrations.AlterField(
            model_name='auditoriainstitucion',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='institucion.institucion'),
        ),
        migrations.AlterField(
            model_name='auditoriainternacion',
            name='internacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='internacion.internacion'),
        ),
        migrations.AlterField(
            model_name='auditoriaintervencion',
            name='intervencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='intervencion.intervencion'),
        ),
        migrations.AlterField(
            model_name='auditoriapersona',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='auditoriausuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
