# Generated by Django 5.2.4 on 2026-03-03 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_alter_auditoriainternacion_internacion'),
        ('expediente', '0019_expedienteinstitucion_unique_expediente_institucion_rol_and_more'),
        ('institucion', '0001_initial'),
        ('internacion', '0007_rename_posse_adiccion_internacion_posee_adiccion'),
        ('intervencion', '0003_alter_intervencion_options_and_more'),
        ('persona', '0006_alter_persona_situacion_habitacional'),
        ('profesional', '0003_alter_profesional_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaexpediente',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_expediente', to='expediente.expediente'),
        ),
        migrations.AlterField(
            model_name='auditoriainstitucion',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_institucion', to='institucion.institucion'),
        ),
        migrations.AlterField(
            model_name='auditoriainternacion',
            name='internacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_internacion', to='internacion.internacion'),
        ),
        migrations.AlterField(
            model_name='auditoriaintervencion',
            name='intervencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_intervencion', to='intervencion.intervencion'),
        ),
        migrations.AlterField(
            model_name='auditoriapersona',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_persona', to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='auditoriaprofesional',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_profesional', to='profesional.profesional'),
        ),
    ]
