# Generated by Django 5.2.4 on 2026-03-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0007_alter_auditoriainternacion_internacion'),
        ('internacion', '0007_rename_posse_adiccion_internacion_posee_adiccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriainternacion',
            name='internacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_internacion', to='internacion.internacion'),
        ),
    ]
