# Generated by Django 5.2.4 on 2026-03-04 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0009_alter_auditoriainternacion_internacion'),
        ('expediente', '0019_expedienteinstitucion_unique_expediente_institucion_rol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaExpedientePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación')], max_length=10)),
                ('expediente_id', models.IntegerField(blank=True, null=True)),
                ('expediente_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('persona_id', models.IntegerField(blank=True, null=True)),
                ('persona_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('rol_id', models.IntegerField(blank=True, null=True)),
                ('rol_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('expediente_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_expediente_persona', to='expediente.expedientepersona')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
