# Generated by Django 5.2.4 on 2026-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0010_auditoriaexpedientepersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaexpedientepersona',
            name='expediente_persona_id_original',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
