# Generated by Django 5.2.4 on 2026-03-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0011_auditoriaexpedientepersona_expediente_persona_id_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoriaexpedientepersona',
            name='expediente_persona',
        ),
    ]
