# Generated by Django 5.2.4 on 2026-03-05 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0012_remove_auditoriaexpedientepersona_expediente_persona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaExpedienteInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente_institucion_id_original', models.IntegerField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Edición'), ('ELIMINAR', 'Eliminación')], max_length=10)),
                ('expediente_id', models.IntegerField(blank=True, null=True)),
                ('expediente_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion_id', models.IntegerField(blank=True, null=True)),
                ('institucion_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('internacion_id', models.IntegerField(blank=True, null=True)),
                ('internacion_descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
