# Generated by Django 5.2.4 on 2026-03-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0013_auditoriaexpedienteinstitucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriausuario',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
