# Generated by Django 5.2.4 on 2025-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250820_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='abreviatura',
            field=models.CharField(max_length=4, unique=True, verbose_name='Nombre abreviado'),
        ),
    ]
