# Generated by Django 5.2.4 on 2026-02-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sede_abreviatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacionHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion_habitacional', models.CharField(max_length=50, verbose_name='Situación Habitacional')),
            ],
            options={
                'verbose_name': 'Situación Habitacional',
                'verbose_name_plural': 'Situaciones Habitacionales',
                'ordering': ['-id'],
            },
        ),
    ]
