# Generated by Django 5.2.4 on 2026-03-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_situacionhabitacional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaprofesional',
            options={'ordering': ['area_profesional'], 'verbose_name': 'Área profesional', 'verbose_name_plural': 'Áreas profesionales'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['genero'], 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['localidad'], 'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='nivel_educativo',
            options={'ordering': ['nivel_educativo'], 'verbose_name': 'Nivel Educativo', 'verbose_name_plural': 'Niveles Educativos'},
        ),
        migrations.AlterModelOptions(
            name='profesion',
            options={'ordering': ['profesion'], 'verbose_name': 'Profesión', 'verbose_name_plural': 'Profesiones'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['rol'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='tipo_documento',
            options={'ordering': ['tipo_documento'], 'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documentos'},
        ),
    ]
