# Generated by Django 5.2.4 on 2026-01-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_persona_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='carnet_unico_discapacidad',
            field=models.BooleanField(default=False, verbose_name='Carnet único de discapacidad'),
        ),
    ]
