# Generated by Django 5.2.4 on 2026-02-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_situacionhabitacional'),
        ('persona', '0005_persona_carnet_unico_discapacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='situacion_habitacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_situacion_habitacional', to='core.situacionhabitacional', verbose_name='Situación habitacional'),
        ),
    ]
